export enum ProjectTypeLabels {
  INTABULARE_TEREN_CONSTRUCTIE = 'Intabulare teren / Constructie',
  INTABULARE_UI = 'Intabulare UI',
  DEZMEMBRARE_ALIPIRE = 'Dezmembrare / Alipire',
  APARTAMENTARE = 'Apartamentare',
  RIDICARE = 'Ridicare',
}

export enum ProjectTypeValues {
  INTABULARE_TEREN_CONSTRUCTIE = 'INTABULARE_TEREN_CONSTRUCTIE',
  INTABULARE_UI = 'INTABULARE_UI',
  DEZMEMBRARE_ALIPIRE = 'DEZMEMBRARE_ALIPIRE',
  APARTAMENTARE = 'APARTAMENTARE',
  RIDICARE = 'RIDICARE',
}
