import { Task } from './columns';

export const mockData: Task[] = [
  {
    id: 'TASK-8782',
    name: "You can't compress the program without quantifying the open-source SSD pixel!",
    status: 'CONTRACTAT',
    label: 'documentation',
    priority: 'medium',
  },
  {
    id: 'TASK-7878',
    name: 'Try to calculate the EXE feed, maybe it will index the multi-byte pixel!',
    status: 'MASURAT',
    label: 'documentation',
    priority: 'medium',
  },
  {
    id: 'TASK-7839',
    name: 'We need to bypass the neural TCP card!',
    status: 'DEPUS',
    label: 'bug',
    priority: 'high',
  },
  {
    id: 'TASK-5562',
    name: 'The SAS interface is down, bypass the open-source pixel so we can back up the PNG bandwidth!',
    status: 'AVIZAT',
    label: 'feature',
    priority: 'medium',
  },
  {
    id: 'TASK-8686',
    name: "I'll parse the wireless SSL protocol, that should driver the API panel!",
    status: 'VERIFICARE_DOCUMENTATIE',
    label: 'feature',
    priority: 'medium',
  },
  {
    id: 'TASK-1280',
    name: 'Use the digital TLS panel, then you can transmit the haptic system!',
    status: 'RESPINS',
    label: 'bug',
    priority: 'high',
  },
  {
    id: 'TASK-7262',
    name: 'The UTF8 application is down, parse the neural bandwidth so we can back up the PNG firewall!',
    status: 'INTOCMIRE_DOCUMENTATIE',
    label: 'feature',
    priority: 'high',
  },
  {
    id: 'TASK-1138',
    name: "Generating the driver won't do anything, we need to quantify the 1080p SMTP bandwidth!",
    status: 'PRELUCARE_MASURATORI',
    label: 'feature',
    priority: 'medium',
  },
  {
    id: 'TASK-7184',
    name: 'We need to program the back-end THX pixel!',
    status: 'PRELUCARE_MASURATORI',
    label: 'feature',
    priority: 'low',
  },
  {
    id: 'TASK-5160',
    name: "Calculating the bus won't do anything, we need to navigate the back-end JSON protocol!",
    status: 'DEPUS',
    label: 'documentation',
    priority: 'high',
  },
  {
    id: 'TASK-5618',
    name: "Generating the driver won't do anything, we need to index the online SSL application!",
    status: 'MASURAT',
    label: 'documentation',
    priority: 'medium',
  },
  {
    id: 'TASK-6699',
    name: "I'll transmit the wireless JBOD capacitor, that should hard drive the SSD feed!",
    status: 'INTOCMIRE_DOCUMENTATIE',
    label: 'documentation',
    priority: 'medium',
  },
  {
    id: 'TASK-2858',
    name: 'We need to override the online UDP bus!',
    status: 'INTOCMIRE_DOCUMENTATIE',
    label: 'bug',
    priority: 'medium',
  },
  {
    id: 'TASK-9864',
    name: "I'll reboot the 1080p FTP panel, that should matrix the HEX hard drive!",
    status: 'MASURAT',
    label: 'bug',
    priority: 'high',
  },
  {
    id: 'TASK-8404',
    name: 'We need to generate the virtual HEX alarm!',
    status: 'DEPUS',
    label: 'bug',
    priority: 'low',
  },
  {
    id: 'TASK-5365',
    name: "Backing up the pixel won't do anything, we need to transmit the primary IB array!",
    status: 'DEPUS',
    label: 'documentation',
    priority: 'low',
  },
  {
    id: 'TASK-1780',
    name: 'The CSS feed is down, index the bluetooth transmitter so we can compress the CLI protocol!',
    status: 'PRELUCARE_MASURATORI',
    label: 'documentation',
    priority: 'high',
  },
  {
    id: 'TASK-6938',
    name: 'Use the redundant SCSI application, then you can hack the optical alarm!',
    status: 'PRELUCARE_MASURATORI',
    label: 'documentation',
    priority: 'high',
  },
  {
    id: 'TASK-9885',
    name: 'We need to compress the auxiliary VGA driver!',
    status: 'INTOCMIRE_DOCUMENTATIE',
    label: 'bug',
    priority: 'high',
  },
  {
    id: 'TASK-3216',
    name: "Transmitting the transmitter won't do anything, we need to compress the virtual HDD sensor!",
    status: 'INTOCMIRE_DOCUMENTATIE',
    label: 'documentation',
    priority: 'medium',
  },
  {
    id: 'TASK-9285',
    name: 'The IP monitor is down, copy the haptic alarm so we can generate the HTTP transmitter!',
    status: 'PRELUCARE_MASURATORI',
    label: 'bug',
    priority: 'high',
  },
  {
    id: 'TASK-1024',
    name: "Overriding the microchip won't do anything, we need to transmit the digital OCR transmitter!",
    status: 'DEPUS',
    label: 'documentation',
    priority: 'low',
  },
  {
    id: 'TASK-7068',
    name: "You can't generate the capacitor without indexing the wireless HEX pixel!",
    status: 'CONTRACTAT',
    label: 'bug',
    priority: 'low',
  },
  {
    id: 'TASK-6502',
    name: "Navigating the microchip won't do anything, we need to bypass the back-end SQL bus!",
    status: 'PRELUCARE_MASURATORI',
    label: 'bug',
    priority: 'high',
  },
  {
    id: 'TASK-5326',
    name: 'We need to hack the redundant UTF8 transmitter!',
    status: 'PRELUCARE_MASURATORI',
    label: 'bug',
    priority: 'low',
  },
  {
    id: 'TASK-6274',
    name: 'Use the virtual PCI circuit, then you can parse the bluetooth alarm!',
    status: 'CONTRACTAT',
    label: 'documentation',
    priority: 'low',
  },
  {
    id: 'TASK-1571',
    name: "I'll input the neural DRAM circuit, that should protocol the SMTP interface!",
    status: 'DEPUS',
    label: 'feature',
    priority: 'medium',
  },
  {
    id: 'TASK-9518',
    name: "Compressing the interface won't do anything, we need to compress the online SDD matrix!",
    status: 'CONTRACTAT',
    label: 'documentation',
    priority: 'medium',
  },
  {
    id: 'TASK-5581',
    name: "I'll synthesize the digital COM pixel, that should transmitter the UTF8 protocol!",
    status: 'INTOCMIRE_DOCUMENTATIE',
    label: 'documentation',
    priority: 'high',
  },
  {
    id: 'TASK-2197',
    name: "Parsing the feed won't do anything, we need to copy the bluetooth DRAM bus!",
    status: 'PRELUCARE_MASURATORI',
    label: 'documentation',
    priority: 'low',
  },
  {
    id: 'TASK-8484',
    name: 'We need to parse the solid state UDP firewall!',
    status: 'DEPUS',
    label: 'bug',
    priority: 'low',
  },
  {
    id: 'TASK-9892',
    name: 'If we back up the application, we can get to the UDP application through the multi-byte THX capacitor!',
    status: 'MASURAT',
    label: 'documentation',
    priority: 'high',
  },
  {
    id: 'TASK-9616',
    name: 'We need to synthesize the cross-platform ASCII pixel!',
    status: 'DEPUS',
    label: 'feature',
    priority: 'medium',
  },
  {
    id: 'TASK-9744',
    name: 'Use the back-end IP card, then you can input the solid state hard drive!',
    status: 'MASURAT',
    label: 'documentation',
    priority: 'low',
  },
  {
    id: 'TASK-1376',
    name: "Generating the alarm won't do anything, we need to generate the mobile IP capacitor!",
    status: 'INTOCMIRE_DOCUMENTATIE',
    label: 'documentation',
    priority: 'low',
  },
  {
    id: 'TASK-7382',
    name: 'If we back up the firewall, we can get to the RAM alarm through the primary UTF8 pixel!',
    status: 'PRELUCARE_MASURATORI',
    label: 'feature',
    priority: 'low',
  },
  {
    id: 'TASK-2290',
    name: "I'll compress the virtual JSON panel, that should application the UTF8 bus!",
    status: 'CONTRACTAT',
    label: 'documentation',
    priority: 'high',
  },
  {
    id: 'TASK-1533',
    name: "You can't input the firewall without overriding the wireless TCP firewall!",
    status: 'MASURAT',
    label: 'bug',
    priority: 'high',
  },
  {
    id: 'TASK-4920',
    name: "Bypassing the hard drive won't do anything, we need to input the bluetooth JSON program!",
    status: 'DEPUS',
    label: 'bug',
    priority: 'high',
  },
  {
    id: 'TASK-5168',
    name: 'If we synthesize the bus, we can get to the IP panel through the virtual TLS array!',
    status: 'DEPUS',
    label: 'feature',
    priority: 'low',
  },
  {
    id: 'TASK-7103',
    name: 'We need to parse the multi-byte EXE bandwidth!',
    status: 'CONTRACTAT',
    label: 'feature',
    priority: 'low',
  },
  {
    id: 'TASK-4314',
    name: 'If we compress the program, we can get to the XML alarm through the multi-byte COM matrix!',
    status: 'DEPUS',
    label: 'bug',
    priority: 'high',
  },
  {
    id: 'TASK-3415',
    name: 'Use the cross-platform XML application, then you can quantify the solid state feed!',
    status: 'PRELUCARE_MASURATORI',
    label: 'feature',
    priority: 'high',
  },
  {
    id: 'TASK-8339',
    name: 'Try to calculate the DNS interface, maybe it will input the bluetooth capacitor!',
    status: 'DEPUS',
    label: 'feature',
    priority: 'low',
  },
  {
    id: 'TASK-6995',
    name: 'Try to hack the XSS bandwidth, maybe it will override the bluetooth matrix!',
    status: 'PRELUCARE_MASURATORI',
    label: 'feature',
    priority: 'high',
  },
  {
    id: 'TASK-8053',
    name: 'If we connect the program, we can get to the UTF8 matrix through the digital UDP protocol!',
    status: 'PRELUCARE_MASURATORI',
    label: 'feature',
    priority: 'medium',
  },
  {
    id: 'TASK-4336',
    name: 'If we synthesize the microchip, we can get to the SAS sensor through the optical UDP program!',
    status: 'PRELUCARE_MASURATORI',
    label: 'documentation',
    priority: 'low',
  },
  {
    id: 'TASK-8790',
    name: "I'll back up the optical COM alarm, that should alarm the RSS capacitor!",
    status: 'MASURAT',
    label: 'bug',
    priority: 'medium',
  },
  {
    id: 'TASK-8980',
    name: 'Try to navigate the SQL transmitter, maybe it will back up the virtual firewall!',
    status: 'CONTRACTAT',
    label: 'bug',
    priority: 'low',
  },
  {
    id: 'TASK-7342',
    name: 'Use the neural CLI card, then you can parse the online port!',
    status: 'INTOCMIRE_DOCUMENTATIE',
    label: 'documentation',
    priority: 'low',
  },
  {
    id: 'TASK-5608',
    name: "I'll hack the haptic SSL program, that should bus the UDP transmitter!",
    status: 'CONTRACTAT',
    label: 'documentation',
    priority: 'low',
  },
  {
    id: 'TASK-1606',
    name: "I'll generate the bluetooth PNG firewall, that should pixel the SSL driver!",
    status: 'MASURAT',
    label: 'feature',
    priority: 'medium',
  },
  {
    id: 'TASK-7872',
    name: "Transmitting the circuit won't do anything, we need to reboot the 1080p RSS monitor!",
    status: 'CONTRACTAT',
    label: 'feature',
    priority: 'medium',
  },
  {
    id: 'TASK-4167',
    name: 'Use the cross-platform SMS circuit, then you can synthesize the optical feed!',
    status: 'CONTRACTAT',
    label: 'bug',
    priority: 'medium',
  },
  {
    id: 'TASK-9581',
    name: "You can't index the port without hacking the cross-platform XSS monitor!",
    status: 'INTOCMIRE_DOCUMENTATIE',
    label: 'documentation',
    priority: 'low',
  },
  {
    id: 'TASK-8806',
    name: 'We need to bypass the back-end SSL panel!',
    status: 'MASURAT',
    label: 'bug',
    priority: 'medium',
  },
  {
    id: 'TASK-6542',
    name: 'Try to quantify the RSS firewall, maybe it will quantify the open-source system!',
    status: 'MASURAT',
    label: 'feature',
    priority: 'low',
  },
  {
    id: 'TASK-6806',
    name: 'The VGA protocol is down, reboot the back-end matrix so we can parse the CSS panel!',
    status: 'CONTRACTAT',
    label: 'documentation',
    priority: 'low',
  },
  {
    id: 'TASK-9549',
    name: "You can't bypass the bus without connecting the neural JBOD bus!",
    status: 'PRELUCARE_MASURATORI',
    label: 'feature',
    priority: 'high',
  },
  {
    id: 'TASK-1075',
    name: "Backing up the driver won't do anything, we need to parse the redundant RAM pixel!",
    status: 'MASURAT',
    label: 'feature',
    priority: 'medium',
  },
  {
    id: 'TASK-1427',
    name: 'Use the auxiliary PCI circuit, then you can calculate the cross-platform interface!',
    status: 'MASURAT',
    label: 'documentation',
    priority: 'high',
  },
  {
    id: 'TASK-1907',
    name: "Hacking the circuit won't do anything, we need to back up the online DRAM system!",
    status: 'PRELUCARE_MASURATORI',
    label: 'documentation',
    priority: 'high',
  },
  {
    id: 'TASK-4309',
    name: 'If we generate the system, we can get to the TCP sensor through the optical GB pixel!',
    status: 'INTOCMIRE_DOCUMENTATIE',
    label: 'bug',
    priority: 'medium',
  },
  {
    id: 'TASK-3973',
    name: "I'll parse the back-end ADP array, that should bandwidth the RSS bandwidth!",
    status: 'PRELUCARE_MASURATORI',
    label: 'feature',
    priority: 'medium',
  },
  {
    id: 'TASK-7962',
    name: 'Use the wireless RAM program, then you can hack the cross-platform feed!',
    status: 'CONTRACTAT',
    label: 'bug',
    priority: 'low',
  },
  {
    id: 'TASK-3360',
    name: "You can't quantify the program without synthesizing the neural OCR interface!",
    status: 'MASURAT',
    label: 'feature',
    priority: 'medium',
  },
  {
    id: 'TASK-9887',
    name: 'Use the auxiliary ASCII sensor, then you can connect the solid state port!',
    status: 'INTOCMIRE_DOCUMENTATIE',
    label: 'bug',
    priority: 'medium',
  },
  {
    id: 'TASK-3649',
    name: "I'll input the virtual USB system, that should circuit the DNS monitor!",
    status: 'DEPUS',
    label: 'feature',
    priority: 'medium',
  },
  {
    id: 'TASK-3586',
    name: 'If we quantify the circuit, we can get to the CLI feed through the mobile SMS hard drive!',
    status: 'DEPUS',
    label: 'bug',
    priority: 'low',
  },
  {
    id: 'TASK-5150',
    name: "I'll hack the wireless XSS port, that should transmitter the IP interface!",
    status: 'CONTRACTAT',
    label: 'feature',
    priority: 'medium',
  },
  {
    id: 'TASK-3652',
    name: 'The SQL interface is down, override the optical bus so we can program the ASCII interface!',
    status: 'INTOCMIRE_DOCUMENTATIE',
    label: 'feature',
    priority: 'low',
  },
  {
    id: 'TASK-6884',
    name: 'Use the digital PCI circuit, then you can synthesize the multi-byte microchip!',
    status: 'CONTRACTAT',
    label: 'feature',
    priority: 'high',
  },
  {
    id: 'TASK-1591',
    name: 'We need to connect the mobile XSS driver!',
    status: 'DEPUS',
    label: 'feature',
    priority: 'high',
  },
  {
    id: 'TASK-3802',
    name: 'Try to override the ASCII protocol, maybe it will parse the virtual matrix!',
    status: 'DEPUS',
    label: 'feature',
    priority: 'low',
  },
  {
    id: 'TASK-7253',
    name: "Programming the capacitor won't do anything, we need to bypass the neural IB hard drive!",
    status: 'INTOCMIRE_DOCUMENTATIE',
    label: 'bug',
    priority: 'high',
  },
  {
    id: 'TASK-9739',
    name: 'We need to hack the multi-byte HDD bus!',
    status: 'MASURAT',
    label: 'documentation',
    priority: 'medium',
  },
  {
    id: 'TASK-4424',
    name: 'Try to hack the HEX alarm, maybe it will connect the optical pixel!',
    status: 'DEPUS',
    label: 'documentation',
    priority: 'medium',
  },
  {
    id: 'TASK-3922',
    name: "You can't back up the capacitor without generating the wireless PCI program!",
    status: 'INTOCMIRE_DOCUMENTATIE',
    label: 'bug',
    priority: 'low',
  },
  {
    id: 'TASK-4921',
    name: "I'll index the open-source IP feed, that should system the GB application!",
    status: 'CONTRACTAT',
    label: 'bug',
    priority: 'low',
  },
  {
    id: 'TASK-5814',
    name: 'We need to calculate the 1080p AGP feed!',
    status: 'INTOCMIRE_DOCUMENTATIE',
    label: 'bug',
    priority: 'high',
  },
  {
    id: 'TASK-2645',
    name: "Synthesizing the system won't do anything, we need to navigate the multi-byte HDD firewall!",
    status: 'PRELUCARE_MASURATORI',
    label: 'documentation',
    priority: 'medium',
  },
  {
    id: 'TASK-4535',
    name: 'Try to copy the JSON circuit, maybe it will connect the wireless feed!',
    status: 'DEPUS',
    label: 'feature',
    priority: 'low',
  },
  {
    id: 'TASK-4463',
    name: 'We need to copy the solid state AGP monitor!',
    status: 'MASURAT',
    label: 'documentation',
    priority: 'low',
  },
  {
    id: 'TASK-9745',
    name: 'If we connect the protocol, we can get to the GB system through the bluetooth PCI microchip!',
    status: 'CONTRACTAT',
    label: 'feature',
    priority: 'high',
  },
  {
    id: 'TASK-2080',
    name: 'If we input the bus, we can get to the RAM matrix through the auxiliary RAM card!',
    status: 'PRELUCARE_MASURATORI',
    label: 'bug',
    priority: 'medium',
  },
  {
    id: 'TASK-3838',
    name: "I'll bypass the online TCP application, that should panel the AGP system!",
    status: 'INTOCMIRE_DOCUMENTATIE',
    label: 'bug',
    priority: 'high',
  },
  {
    id: 'TASK-1340',
    name: 'We need to navigate the virtual PNG circuit!',
    status: 'PRELUCARE_MASURATORI',
    label: 'bug',
    priority: 'medium',
  },
  {
    id: 'TASK-6665',
    name: 'If we parse the monitor, we can get to the SSD hard drive through the cross-platform AGP alarm!',
    status: 'CONTRACTAT',
    label: 'feature',
    priority: 'low',
  },
  {
    id: 'TASK-7585',
    name: 'If we calculate the hard drive, we can get to the SSL program through the multi-byte CSS microchip!',
    status: 'INTOCMIRE_DOCUMENTATIE',
    label: 'feature',
    priority: 'low',
  },
  {
    id: 'TASK-6319',
    name: 'We need to copy the multi-byte SCSI program!',
    status: 'INTOCMIRE_DOCUMENTATIE',
    label: 'bug',
    priority: 'high',
  },
  {
    id: 'TASK-4369',
    name: 'Try to input the SCSI bus, maybe it will generate the 1080p pixel!',
    status: 'INTOCMIRE_DOCUMENTATIE',
    label: 'bug',
    priority: 'high',
  },
  {
    id: 'TASK-9035',
    name: 'We need to override the solid state PNG array!',
    status: 'CONTRACTAT',
    label: 'documentation',
    priority: 'low',
  },
  {
    id: 'TASK-3970',
    name: "You can't index the transmitter without quantifying the haptic ASCII card!",
    status: 'PRELUCARE_MASURATORI',
    label: 'documentation',
    priority: 'medium',
  },
  {
    id: 'TASK-4473',
    name: "You can't bypass the protocol without overriding the neural RSS program!",
    status: 'PRELUCARE_MASURATORI',
    label: 'documentation',
    priority: 'low',
  },
  {
    id: 'TASK-4136',
    name: "You can't hack the hard drive without hacking the primary JSON program!",
    status: 'CONTRACTAT',
    label: 'bug',
    priority: 'medium',
  },
  {
    id: 'TASK-3939',
    name: 'Use the back-end SQL firewall, then you can connect the neural hard drive!',
    status: 'MASURAT',
    label: 'feature',
    priority: 'low',
  },
  {
    id: 'TASK-2007',
    name: "I'll input the back-end USB protocol, that should bandwidth the PCI system!",
    status: 'INTOCMIRE_DOCUMENTATIE',
    label: 'bug',
    priority: 'high',
  },
  {
    id: 'TASK-7516',
    name: 'Use the primary SQL program, then you can generate the auxiliary transmitter!',
    status: 'MASURAT',
    label: 'documentation',
    priority: 'medium',
  },
  {
    id: 'TASK-6906',
    name: 'Try to back up the DRAM system, maybe it will reboot the online transmitter!',
    status: 'MASURAT',
    label: 'feature',
    priority: 'high',
  },
  {
    id: 'TASK-5207',
    name: 'The SMS interface is down, copy the bluetooth bus so we can quantify the VGA card!',
    status: 'DEPUS',
    label: 'bug',
    priority: 'low',
  },
];
